server:
  port: 8080

spring:
  application:
    name: baseline-service-cavm
    
    
security:
  basic:
    enable: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*' 


hystrix:
  threadpool:
    default:
      coreSize: 35
      maximumSize: 35
  command:
    createRevenueGrid:
      execution:
        esilation:
          thread:
            timeoutInMilliseconds: 1500
          semaphore:
            maxConcurretRequest: 500
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
            


